# Generated by Django 2.0.5 on 2018-05-19 19:18

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mk_content',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
