# Generated by Django 2.0.5 on 2018-05-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_mk_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='content',
        ),
    ]
